#!/bin/bash -e

die() {
    echo "$@"
    exit
}

app=$1

[ -z "$app" ] && die "Usage: $0 <application name>"

[[ "$app" =~ ^[a-z0-9_]+$ ]] || die "The application name should consist only of a-z, 0-9 or _ charaters."

echo "Initializing resources for $app.";

# KMS alias
alias=$app-secrets
found=`aws kms list-aliases --query "Aliases[?AliasName == 'alias/$alias'] | [0].TargetKeyId" --output text`
if [ "$found" == "None" ]; then
    echo 'Making new key'
    key_id=`aws kms create-key --query 'KeyMetadata.KeyId' --output text`
    echo "Making new alias $alias"
    aws kms create-alias --target-key-id $key_id --alias-name "alias/$alias"
else
    echo "Found existing alias $alias, key $found"
    key_id=$found
fi

# S3 bucket
bucket=$app-secrets
found=`aws s3api list-buckets --query "Buckets[?Name == '$bucket'] | [0].Name" --output text`
if [ "$found" == "None" ]; then
    echo "Creating bucket $bucket"
    made=`aws s3api create-bucket --bucket $bucket --acl private --output text`
else
    echo "Found existing bucket $bucket"
fi

# IAM Role for instances
instancerole=$app-secrets-instances
found=`aws iam list-roles --query "Roles[?RoleName == '$instancerole'] | [0].RoleId" --output text`
if [ "$found" == "None" ]; then
    echo "Creating new role for instances: $instancerole"
    trustpolicy=`mktemp`
    cat <<-TRUSTPOLICY >>$trustpolicy
	{
	  "Id": "key-$app-secrets-instance-trust-policy",
	  "Version": "2012-10-17",
	  "Statement": [
	    {
	      "Effect": "Allow",
	      "Principal": { "Service" : "ec2.amazonaws.com" },
	      "Action": "sts:AssumeRole"
	    }
	  ]
	}
	TRUSTPOLICY
    response=`aws iam create-role --role-name $instancerole --assume-role-policy-document file://$trustpolicy`
    accesspolicy=`mktemp`
    cat <<-ACCESSPOLICY >> $accesspolicy
	{
	  "Id": "key-$app-secrets-instance-access-policy",
	  "Version": "2012-10-17",
	  "Statement": [
	    {
	        "Effect" : "Allow",
	        "Action" : "s3:GetObject",
	        "Resource" : "arn:aws:s3:::$bucket"
	    }
	  ]
	}
	ACCESSPOLICY
    aws iam put-role-policy --role-name $instancerole --policy-name $app-s3-access --policy-document file://$accesspolicy
    rm $trustpolicy
    rm $accesspolicy
else
    echo "Found existing role $instancerole ($found)"
fi
exit
# Instance profile
# Add role to instance profile

# Role for users (or groups)
# Assign role to users/groups

