#!/bin/sh -e

# retrieve-aws-secrets
#   Retrieve an encrypted secrets file from s3 and print it to stdout.

die() {
    echo "$@"
    exit
}
app=$1
[ -z "$app" ] && die "Missing app.  Usage: $0 <app>";

s3_key=$app-aws-secrets
s3_bucket=$app-secrets
kms_alias=$app-secrets

tmp=`mktemp -d`

aws s3api get-object --bucket $s3_bucket --key $s3_key $tmp/out > /tmp/errs

aws kms decrypt  --ciphertext-blob fileb://$tmp/out --output text --query Plaintext | base64 --decode

rm -rf $tmp
