#!/bin/sh -e

# retrieve-env
#   Retrieve a file from s3, decrypt it and add it to the envirionment
#
# Synopsis:
#   retrieve-env <s3_key>
#   <s3_key> is a key in S3.  Default is .env.

s3_key=${1:-bduggan-test}
kms_key=bduggan-test
s3_bucket=bduggan-test-bucket

die() {
    echo $@;
    exit
}

tmp=`mktemp -d`

aws s3api get-object --bucket $s3_bucket --key $s3_key $tmp/out > /tmp/errs

key_id=`aws kms list-aliases --output text --query "Aliases[?AliasName=='alias/$kms_key'].TargetKeyId | [0]"`

aws kms decrypt  --ciphertext-blob fileb://$tmp/out --output text --query Plaintext | base64 --decode

rm -rf $tmp
