#!/bin/sh -e

# send-aws-secrets
#   Encrypt a file using a KMS key alias, then send it to an s3 bucket.

die() {
    echo "$@"
    exit
}
app=$1
secrets_file=$2
[ -z "$app" ] && die "Missing app.  Usage: $0 <app> <filename>";
[ -z "$secrets_file" ] && die "Missing filename.  Usage: $0 <app> <filename>";

src=$secrets_file
s3_bucket=$app-secrets
s3_key=$app-aws-secrets
kms_alias=$app-secrets

tmp=`mktemp -d`
encrypted=$tmp/data.enc

key_id=`aws kms list-aliases --output text --query "Aliases[?AliasName=='alias/$kms_alias'].TargetKeyId | [0]"`

aws kms encrypt \
    --key-id $key_id \
    --plaintext fileb://$src \
    --query CiphertextBlob \
    --output text \
    | base64 --decode \
    > $encrypted

aws s3api put-object \
    --bucket $s3_bucket \
    --key $s3_key \
    --acl private \
    --body $encrypted \
    --output text \
    --query 'None' \
    | egrep -v '^None$' || true

rm -rf $tmp
